_format_version: "2.1"

consumers:
  - username: kcc
    custom_id: kcc
  - username: iamusr
    custom_id: iamusr

basicauth_credentials:
  - consumer: kcc
    username: kcc
    password: "Kcc@123!"
  - consumer: iamusr
    username: iamusr
    password: "iamusr@123!"

services:

# ================= AUTH =================
- name: auth-service
  url: http://auth-service.kcim.svc.cluster.local:9090
  routes:
    - name: auth-route
      paths:
        - ~/api/auth
      strip_path: false

- name: auth-detail-service
  url: http://auth-service.kcim.svc.cluster.local:9090
  plugins:
    - name: custom-auth
      config:
        authVerifyTokenEndpoint: http://auth-service.kcim.svc.cluster.local:9090/verifyToken
  routes:
    - name: auth-detail-route
      paths:
        - ~/api/auth-detail
      strip_path: false


# ================= KCIM =================
- name: kcim-service
  url: http://kcim-service.kcim.svc.cluster.local:9091
  plugins:
    - name: custom-auth
      config:
        authVerifyTokenEndpoint: http://auth-service.kcim.svc.cluster.local:9090/verifyToken
  routes:

    - name: dropdown-route
      paths:
        - ~/api/dropdown
      strip_path: false

    - name: kcim-service-route
      paths:
        - ~/api/kcim-service
      strip_path: false

    - name: kcim-menu-route
      paths:
        - ~/api/cim-menu
      strip_path: false

    - name: kcim-provider-route
      paths:
        - ~/api/kcim-provider
      strip_path: false


# ================= TRANSPORT =================
- name: transport-service
  url: http://transport-service.kcim.svc.cluster.local:9092
  plugins:
    - name: custom-auth
      config:
        authVerifyTokenEndpoint: http://auth-service.kcim.svc.cluster.local:9090/verifyToken
  routes:

    - name: transport-service-route
      paths:
        - ~/api/transport-service
      strip_path: false

    - name: transport-menu-route
      paths:
        - ~/api/transport-menu
      strip_path: false

    - name: transport-dropdown-route
      paths:
        - ~/api/transport-dropdown
      strip_path: false


# ================= CCMS =================
- name: ccms-service
  url: http://ccms-service.kcim.svc.cluster.local:9093
  plugins:
    - name: custom-auth
      config:
        authVerifyTokenEndpoint: http://auth-service.kcim.svc.cluster.local:9090/verifyToken
  routes:

    - name: ccms-menu-route
      paths:
        - ~/api/ccms-menu
      strip_path: false

    - name: ccms-service-route
      paths:
        - ~/api/ccms-service
      strip_path: false

    - name: ccms-dropdown-route
      paths:
        - ~/api/ccms-dropdown
      strip_path: false


# ================= ADMIN =================
- name: admin-service
  url: http://admin-service.kcim.svc.cluster.local:9095
  plugins:
    - name: custom-auth
      config:
        authVerifyTokenEndpoint: http://auth-service.kcim.svc.cluster.local:9090/verifyToken
  routes:

    - name: admin-menu-route
      paths:
        - ~/api/admin-menu
      strip_path: false

    - name: admin-service-route
      paths:
        - ~/api/admin-service
      strip_path: false

    - name: admin-dropdown-route
      paths:
        - ~/api/admin-dropdown
      strip_path: false

    - name: iam-service-route
      paths:
        - ~/api/iam-service
      strip_path: false

    - name: admin-health-route
      paths:
        - ~/api/admin-health
      strip_path: false








