apiVersion: v1
kind: Namespace
metadata:
  name: kcim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: kcim
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
        - name: admin-service
          image: admin-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9095
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: kcim
spec:
  type: ClusterIP
  selector:
    app: admin-service
  ports:
    - name: http
      port: 9095
      targetPort: 9095
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: kcim
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: kcim
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: http
      port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccms-service
  namespace: kcim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccms-service
  template:
    metadata:
      labels:
        app: ccms-service
    spec:
      containers:
        - name: ccms-service
          image: ccms-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9093
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            # PostgreSQL (ต้องมี secret pg-secret)
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: DB_NAME
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: DB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: DB_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: ccms-service
  namespace: kcim
spec:
  type: ClusterIP
  selector:
    app: ccms-service
  ports:
    - name: http
      port: 9093
      targetPort: 9093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcim-service
  namespace: kcim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcim-service
  template:
    metadata:
      labels:
        app: kcim-service
    spec:
      containers:
        - name: kcim-service
          image: kcim-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9091
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
---
apiVersion: v1
kind: Service
metadata:
  name: kcim-service
  namespace: kcim
spec:
  type: ClusterIP
  selector:
    app: kcim-service
  ports:
    - name: http
      port: 9091
      targetPort: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcim3-web
  namespace: kcim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcim3-web
  template:
    metadata:
      labels:
        app: kcim3-web
    spec:
      containers:
        - name: kcim3-web
          image: teegolf/kcim3:3.0.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kcim3-web
  namespace: kcim
spec:
  type: ClusterIP
  selector:
    app: kcim3-web
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transport-service
  namespace: kcim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transport-service
  template:
    metadata:
      labels:
        app: transport-service
    spec:
      containers:
        - name: transport-service
          image: transport-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9092
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
---
apiVersion: v1
kind: Service
metadata:
  name: transport-service
  namespace: kcim
spec:
  type: ClusterIP
  selector:
    app: transport-service
  ports:
    - name: http
      port: 9092
      targetPort: 9092


