apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  namespace: kcim
type: Opaque
stringData:
  POSTGRES_USER: ciadm
  POSTGRES_PASSWORD: ciadm@
  POSTGRES_DB: kcimdbu
  POSTGRES_HOST: 192.168.0.248

